server:
  port: 9988
spring:
  freemarker:
    suffix: .html
  datasource:
    url: jdbc:mysql:///test_demo?useSSL=false&serverTimezone=CST
    username: root
    password: abc123456
    filters: stat
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.springboot.model
  mapper-locations: classpath:mapper/*.xml
log4j:
  rootLogger: INFO,stdout
  logger: com.springboottest.dao